# Site settings
title: Static Webpages Portfolio
email: 2081439477@qq.com
description: A blog showcasing some of my beginning front-end web development work.
baseurl: "/jekyll-portfolio"
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Yongren Wang" # Set default author name
      categories: "Front-End Web Development"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
